# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_editor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBEditor(object):
    def setupUi(self, DBEditor):
        DBEditor.setObjectName("DBEditor")
        DBEditor.resize(684, 565)
        self.centralwidget = QtWidgets.QWidget(DBEditor)
        self.centralwidget.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_file_button.setObjectName("open_file_button")
        self.verticalLayout.addWidget(self.open_file_button)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.half_2 = QtWidgets.QHBoxLayout()
        self.half_2.setObjectName("half_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.half_2.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.half_2, 0, 1, 1, 1)
        DBEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DBEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        DBEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DBEditor)
        self.statusbar.setObjectName("statusbar")
        DBEditor.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(DBEditor)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(DBEditor)
        self.actionSave.setObjectName("actionSave")
        self.actionCreate_table = QtWidgets.QAction(DBEditor)
        self.actionCreate_table.setObjectName("actionCreate_table")
        self.actionSelect = QtWidgets.QAction(DBEditor)
        self.actionSelect.setObjectName("actionSelect")
        self.actionall_columns = QtWidgets.QAction(DBEditor)
        self.actionall_columns.setObjectName("actionall_columns")
        self.actionInformation = QtWidgets.QAction(DBEditor)
        self.actionInformation.setObjectName("actionInformation")
        self.menuFile.addAction(self.actionCreate_table)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionSelect)
        self.menuView.addAction(self.actionall_columns)
        self.menu.addAction(self.actionInformation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(DBEditor)
        QtCore.QMetaObject.connectSlotsByName(DBEditor)

    def retranslateUi(self, DBEditor):
        _translate = QtCore.QCoreApplication.translate
        DBEditor.setWindowTitle(_translate("DBEditor", "DB Editor Loggined"))
        self.open_file_button.setText(_translate("DBEditor", "open file"))
        self.menuFile.setTitle(_translate("DBEditor", "File"))
        self.menuEdit.setTitle(_translate("DBEditor", "Edit"))
        self.menuView.setTitle(_translate("DBEditor", "View"))
        self.menu.setTitle(_translate("DBEditor", "Help"))
        self.actionOpen.setText(_translate("DBEditor", "Open"))
        self.actionSave.setText(_translate("DBEditor", "Save"))
        self.actionCreate_table.setText(_translate("DBEditor", "Create table"))
        self.actionSelect.setText(_translate("DBEditor", "Select"))
        self.actionall_columns.setText(_translate("DBEditor", "all columns"))
        self.actionInformation.setText(_translate("DBEditor", "Information"))
